### ISSUE TITLE
Unable to find suitable version for angular-ui-router

### ISSUE THREAD

**Issue by askdaddy** [sovanna/angular-material-sidenav#41]
When I `bower install angular-material-sidenav --save` got

```
 "id": "ECONFLICT",
  "level": "error",
  "data": {},
  "message": "Unable to find suitable version for angular-ui-router",
  "stacktrace": "angular-ui-router: Unable to find suitable version for angular-ui-router\n    at createError (C:\\Users\\humen\\AppData\\Roaming\\nvm\\v4.4.7\\node_modules\\bower\\lib\\util\\createError.js:4:15)\n    at Manager._electSuitable (C:\\Users\\humen\\AppData\\Roaming\\nvm\\v4.4.7\\node_modules\\bower\\lib\\core\\Manager.js:823:15)\n    at C:\\Users\\humen\\AppData\\Roaming\\nvm\\v4.4.7\\node_modules\\bower\\lib\\core\\Manager.js:609:25\n    at _fulfilled (C:\\Users\\humen\\AppData\\Roaming\\nvm\\v4.4.7\\node_modules\\bower\\lib\\node_modules\\q\\q.js:834:54)\n    at self.promiseDispatch.done (C:\\Users\\humen\\AppData\\Roaming\\nvm\\v4.4.7\\node_modules\\bower\\lib\\node_modules\\q\\q.js:863:30)\n    at Promise.promise.promiseDispatch (C:\\Users\\humen\\AppData\\Roaming\\nvm\\v4.4.7\\node_modules\\bower\\lib\\node_modules\\q\\q.js:796:13)\n    at C:\\Users\\humen\\AppData\\Roaming\\nvm\\v4.4.7\\node_modules\\bower\\lib\\node_modules\\q\\q.js:556:49\n    at runSingle (C:\\Users\\humen\\AppData\\Roaming\\nvm\\v4.4.7\\node_modules\\bower\\lib\\node_modules\\q\\q.js:137:13)\n    at flush (C:\\Users\\humen\\AppData\\Roaming\\nvm\\v4.4.7\\node_modules\\bower\\lib\\node_modules\\q\\q.js:125:13)\n    at nextTickCallbackWith0Args (node.js:420:9)"
}]

```

**Comment by askdaddy** [comment]
I have angular-ui-router 0.3.1 installed
